[project]
name = "face-points"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "albumentations>=1.4,<2.0",
    "numpy<2.0",
    "opencv-python",
    "pandas",
    "pillow",
    "torch==2.1.2",
    "torchvision==0.16.2",
    "torchaudio==2.1.2",
    "tqdm",
]
